#!/usr/bin/env python

from throwablefirefox.openvpn import OpenVPN
from throwablefirefox.networknamespace import NetworkNamespace
from throwablefirefox.tools import subdl, Peerflix, VLC
from throwablefirefox.waitfor import wait_for
from colorama import Fore, Back, Style
import sys


def info(message):
    print(f"{Fore.RED}{message}{Style.RESET_ALL}")

SUITABLE_SIZE = 10000000

if __name__ == "__main__":
    magnet = sys.argv[1]

    with NetworkNamespace(name="peerflix") as network_namespace:
        with OpenVPN(network_namespace=network_namespace, country="Sweden"):
            with Peerflix(magnet=magnet) as peerflix:
                url = peerflix.url

                info(f"Waiting for video file to reach suitable size")
                wait_for(lambda: peerflix.video_file_path.stat().st_size  >= SUITABLE_SIZE, timeout=60)

                info("Downloading subtitles...")
                subtitles_file_path = subdl(peerflix.video_file_path)

                info("Playing video... ")
                vlc = VLC(url=url, subtitles_file_path=subtitles_file_path)
                vlc.start()
                vlc.wait()
