#!/usr/bin/env python

from throwablefirefox.firefox import Firefox, Profile
from throwablefirefox.networknamespace import NetworkNamespace
from throwablefirefox.openvpn import OpenVPN

if __name__ == "__main__":
    with NetworkNamespace(name="toto") as network_namespace:
        with OpenVPN(network_namespace=network_namespace, country="Sweden"):
            with Profile.throwable(network_namespace=network_namespace) as profile:
                firefox = Firefox.start(profile, private=True)
                firefox.wait()

#    bookmarks = [
#
#    ]
#
#    urls = [
#        IP_ADDON_URL,
#        ADBLOCK_ADDON_URL
#    ]

    #extension = Extension("/tmp/tmpk4a0gvdo/show_external_ip-1.0.6-an+fx.xpi")
    #print(extension.id)

#    with NetworkNamespace(name="toto") as network_namespace:
#        with OpenVPN(network_namespace=network_namespace, country="Sweden"):
#            with Profile.throwable(network_namespace=network_namespace) as profile:
#                for url in urls:
#                    extension = Extension.download(url)
#                    profile.install_extension(extension, pre_start=True)
#
#                for bookmark in bookmarks:
#                    profile.add_bookmark(bookmark)
#
#                firefox = Firefox.start(profile, private=True)
#                firefox.wait()
